### ISSUE TITLE
Channel list unusuable when in VC

### ISSUE THREAD

**Issue by rauenzi** [FeoreV/Themes#1]
When in voice chat and/or sharing screen the account container panels separate and hover over the channel list making it near-impossible to use.

![image](https://github.com/FeoreV/Themes/assets/6865942/92dd46bf-f83c-4d1f-a3ec-2548f457c723)

**Comment by FeoreV** [comment]
![image](https://github.com/FeoreV/Themes/assets/81682869/07f7580e-b4e0-4ec0-9a6c-9feeef381b2a)
If you didn't resize the window vertically, then everything should work fine. I don't really understand why everything looks like this.

Is the discord client version stable? Screenshot taken this week?

**Comment by rauenzi** [comment]
Discord stable and screenshot taken as I opened this issue. My monitor resolution is 1440p

**Comment by Matters86** [comment]
Hello sadly i have the same issue it seems 
![grafik](https://github.com/FeoreV/Themes/assets/143445279/95266a02-436f-4a5a-a6cd-29954ac9b42f)
Screenshot from right now

Is it an issue duo to betterdiscord Window setting?
![grafik](https://github.com/FeoreV/Themes/assets/143445279/3d89b79b-6b9f-4bd1-a2c5-853ba687b923)

**Comment by FeoreV** [comment]
> Hello sadly i have the same issue it seems ![grafik](https://user-images.githubusercontent.com/143445279/280554560-95266a02-436f-4a5a-a6cd-29954ac9b42f.png) Screenshot from right now
> 
> Is it an issue duo to betterdiscord Window setting? ![grafik](https://user-images.githubusercontent.com/143445279/280554678-3d89b79b-6b9f-4bd1-a2c5-853ba687b923.png)

This is due to the plugin for enabling/disabling activity. I'll fix it today

**Comment by FeoreV** [comment]
> Discord stable and screenshot taken as I opened this issue. My monitor resolution is 1440p

![image](https://github.com/FeoreV/Themes/assets/81682869/7e8d8fae-b7c5-47da-8afb-41bcde9f592f) (in 2k)
I think it's fixed

**Comment by FeoreV** [comment]
> Discord stable and screenshot taken as I opened this issue. My monitor resolution is 1440p

![image](https://github.com/FeoreV/Themes/assets/81682869/7d7eb57c-5ccc-4d57-a7e7-4a1ade265c6d) (in 2k)
fixed, i think

**Comment by Matters86** [comment]
Sorry to bother you is it possible to make it "locked" so nothing can be behind those windows? 

And do you have a Discord Server to post stuff like that as that is not really an issue? :)

![grafik](https://github.com/FeoreV/Themes/assets/143445279/426141c3-662d-47c3-a9eb-0673d15ab62d)

**Comment by FeoreV** [comment]
> Sorry to bother you is it possible to make it "locked" so nothing can be behind those windows?
> 
> And do you have a Discord Server to post stuff like that as that is not really an issue? :)
> 
> ![grafik](https://user-images.githubusercontent.com/143445279/280807487-426141c3-662d-47c3-a9eb-0673d15ab62d.png)

Yes. Write to me personally. You can find a link to me and the discord server in theme.
![image](https://github.com/FeoreV/Themes/assets/81682869/df59fdac-66e1-4d08-8648-7a91dba3e0f5)
