### ISSUE TITLE
No Themes settings button in FVUI

### ISSUE THREAD

**Issue by shawny43** [FeoreV/Themes#3]
No Themes settings button in FVUI, is pretty embarrassant.
![image](https://github.com/FeoreV/Themes/assets/53010077/c81adcbc-222b-43e3-be74-1aebaf05e991)

**Comment by FeoreV** [comment]
> No Themes settings button in FVUI, is pretty embarrassant.

![image](https://github.com/FeoreV/Themes/assets/81682869/a51ccf65-efda-462a-b935-b2c769736ed3)
The settings button is present only for plugins. Editing settings occurs through any text editor.

**Comment by FeoreV** [comment]
> No Themes settings button in FVUI, is pretty embarrassant. ![image](https://user-images.githubusercontent.com/53010077/281216595-c81adcbc-222b-43e3-be74-1aebaf05e991.png)

I'm more confused by what's happening with the panel on the left. Do you use any plugins or other themes that change settings?

**Comment by shawny43** [comment]
Plugin and theme repo are enabled but idk why FVUI just broke himself.

**Comment by FeoreV** [comment]
> Plugin and theme repo are enabled but idk why FVUI just broke himself. There a way to put BD logs here? Idk if BD got logs seriously.

Oh, I understand. I'll fix it today
