### ISSUE TITLE
theme is buggy

### ISSUE THREAD

**Issue by VaporeonScripts** [FeoreV/Themes#7]
please fix the bugs in the theme

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/d2e2fc7f-92f8-4868-92d2-88c37fd639ac)

**Comment by VaporeonScripts** [comment]
and maybe add a custom background

**Comment by FeoreV** [comment]
![image](https://github.com/user-attachments/assets/9ee5dfc0-3048-4414-bbd6-9aba13702b4a)
For me, everything is in working 
For customization use https://bdeditor.dev/theme/fvui
In case of any problems when using the theme, please write to me in DM
