### ISSUE TITLE
"Friend card" cuts off messages when discord is on small(vertical) display

### ISSUE THREAD

**Issue by Netsurfer36** [FeoreV/Themes#8]
I have a vertical mounted display and discord is always on that display. Yesterday i noticed that the "Friend card" is on top of the direct messages making them unable to read. Maybe make it resizable or that you can minimize it.

![Screenshot 2024-11-02 103058](https://github.com/user-attachments/assets/fb332169-4d28-4b80-ba3b-bf7d88b82ff5)

**Comment by FeoreV** [comment]
![image](https://github.com/user-attachments/assets/5fa95f04-9903-4b2b-ada1-0edca2bd8c64)
You can always hide the user panel
